---
- include_tasks: linux.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian' or ansible_os_family == 'Alpine'

- include_tasks: mac.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
